---
- name: install nginx
  apt: name=nginx state=installed

- name: write our nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: write our /etc/nginx/sites-available/default
  template: src=default-site.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: deploy website content
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html

- name: install Apache
  apt: name=apache2 update_cache=yes state=installed

- name: NodeJS | Install ppa key
  apt_key: id=68576280 url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present validate_certs={{ nodejs_validate_certs }}
- name: NodeJS | Remove launchpad ppa
  apt_repository: repo=ppa:chris-lea/node.js state=absent
- name: NodeJS | Install ppa
  apt_repository: repo="{{ item }}" validate_certs={{ nodejs_validate_certs }}
  with_items:
    - "deb https://deb.nodesource.com/{{ nodejs_branch }} {{ nodejs_distribution_release or ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/{{ nodejs_branch }} {{ nodejs_distribution_release or ansible_distribution_release }} main"
- name: NodeJS | Install package
  apt: name=nodejs state={{ nodejs_apt_state }} force=yes

- name: NodeJS | NPM | Configure proxy
  shell: npm config set proxy {{ npm_proxy }}
  when: npm_proxy is defined

- name: NodeJS | NPM | Configure registry
  shell: npm config set registry {{ nodejs_npm_registry }}
  when: nodejs_npm_registry != "https://registry.npmjs.org/"

## Install global packages
- name: NodeJS | NPM | Install global packages
  npm: name={{ item }} global=yes state=present registry={{ nodejs_npm_registry }}
  with_items: "express"
