---
- hosts: web 
  sudo: yes
  tasks:
      - name: Install nginx web server
        apt: pkg=nginx state=installed update_cache=yes
        with_items:
            - start nginx
      - name: Make sure nginx is started and configure it to run at boot.
        service: name=nginx state=started enabled=yes
